apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  initdb.sql: |
    create database if not exists `auth`;
    create database if not exists `catalog`;
    create database if not exists `orders`;
    create user 'root'@'localhost' identified by 'root';
    grant all on *.*  to 'root'@'%';