apiVersion: v1
kind: ConfigMap
metadata:
  name: config-data
data:
  initdb.sql: |
    create database if not exists `auth`;
    create database if not exists `catalog`;
    create database if not exists `orders`;
    create user 'root'@'localhost' identified by 'root';
    grant all on *.*  to 'root'@'%';
  
  EUREKA_APP_NAME: eureka-server
  GATEWAY_APP_NAME: api-gateway-server
  AUTH_APP_NAME: auth-server
  CATALOG_APP_NAME: catalog-server
  ORDER_APP_NAME: order-server
  
  EUREKA_PORT: "8070"
  EUREKA_DEPLOYED_PORT: "30536"
  AUTH_PORT: "8080"
  AUTH_DEPLOYED_PORT: "31240"
  GATEWAY_PORT: "8072"
  GATEWAY_DEPLOYED_PORT: "32457"
  CATALOG_PORT: "8081"
  CATALOG_DEPLOYED_PORT: "31836"
  ORDER_PORT: "8082"
  ORDER_DEPLOYED_PORT: "30106"
  
  EUREKA_HOSTNAME: localhost
  EUREKA_HOSTNAME_DEPLOYED: eureka-server
  
  AUTH_DATABASE_URL: jdbc:mysql://mysql/auth
  CATALOG_DATABASE_URL: jdbc:mysql://mysql/catalog
  ORDER_DATABASE_URL: jdbc:mysql://mysql/orders
