apiVersion: v1
kind: ConfigMap
metadata:
  name: config-data
data:
  initdb.sql: |
    create database if not exists `auth`;
    create database if not exists `catalog`;
    create database if not exists `orders`;
    create user 'root'@'localhost' identified by 'root';
    grant all on *.*  to 'root'@'%';
  
  EUREKA_APP_NAME: eureka-server
  GATEWAY_APP_NAME: api-gateway-server
  AUTH_APP_NAME: auth-server
  CATALOG_APP_NAME: catalog-server
  ORDER_APP_NAME: order-server
  
  EUREKA_PORT: "8070"
  EUREKA_DEPLOYED_PORT: "31824"
  AUTH_PORT: "8080"
  AUTH_DEPLOYED_PORT: "32160"
  GATEWAY_PORT: "8072"
  GATEWAY_DEPLOYED_PORT: "31131"
  CATALOG_PORT: "8081"
  CATALOG_DEPLOYED_PORT: "31526"
  ORDER_PORT: "8082"
  ORDER_DEPLOYED_PORT: "31505"
  PHOTO_UPLOAD_PORT: "8085"
  PHOTO_DEPLOYED_PORT: "30979"
  CLIENT_PORT: "4200"
  CLIENT_DEPLOYED_PORT: "32021"
  MYSQL_PORT: "3306"
  MYSQL_DEPLOYED_PORT: "31590"
  
  EUREKA_HOSTNAME: localhost
  EUREKA_HOSTNAME_DEPLOYED: eureka-server
  
  AUTH_DATABASE_URL: jdbc:mysql://mysql/auth
  CATALOG_DATABASE_URL: jdbc:mysql://mysql/catalog
  ORDER_DATABASE_URL: jdbc:mysql://mysql/orders
