kind: Service
apiVersion: v1
metadata:
  name: eureka-server
spec:
  selector:
    app: eureka-server
  ports:
  - protocol: TCP
    port: 8070
    nodePort: 30000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: eureka-server
  name: eureka-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  strategy: {}
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
      - image: 2504998/eureka-server:latest
        name: eureka-server
        resources: {}
        imagePullPolicy: Never
        env:
          - name: EUREKA_APP_NAME
            value: "eureka-server"
          - name: EUREKA_PORT
            value: "8070"
          - name: EUREKA_HOSTNAME
            value: "localhost"
status: {}